// apps/partner-angular/src/app/components/route-one/route-one.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'pa-route-one',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './route-one.component.html',
})
export class RouteOneComponent implements OnInit {

  ngOnInit(): void {
    window.dispatchEvent(new CustomEvent('perch-widget:init'));
  }
}

<div class="perch-widget" widget-id="xxDu9Zga">
  <!-- Replace the inner content with custom loader -->
  <div class="perch-widget-loading-indicator" style="text-align: center;">Loading...</div>
</div>

// apps/partner-vue/src/app/views/route-one/RouteOne.vue
<script setup lang="ts">
import { onMounted } from 'vue'

onMounted(() => {
  window.dispatchEvent(new CustomEvent('perch-widget:init'));
})
</script>

<template>
  <div class="perch-widget" widget-id="xxDu9Zga">
    <!-- Replace the inner content with custom loader -->
    <div class="perch-widget-loading-indicator" style="text-align: center;">Loading...</div>
  </div>
</template>

<style scoped></style>
